"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Tunnit.py']
#DATA_FILES = ['Tunnit.xib', 'src']
DATA_FILES = ['src']
OPTIONS = {}

setup(
    app=APP,
    name='Tunnit',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
